# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GUI_main(object):
    def setupUi(self, GUI_main):
        GUI_main.setObjectName("GUI_main")
        GUI_main.resize(800, 500)
        # GUI_main.setStyleSheet("background-image: url(E:/others/others/GUI/GUIimage/BackGround.jpg);")
        self.label = QtWidgets.QLabel(GUI_main)
        self.label.setGeometry(QtCore.QRect(280, 10, 221, 101))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:/others/others/GUI/GUIimage/logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(GUI_main)
        self.pushButton.setGeometry(QtCore.QRect(320, 150, 131, 51))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("border-image: url(E:/others/others/GUI/GUIimage/Start.png);\n"
"background-color: transparent;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(GUI_main)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 230, 131, 51))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-image: url(E:/others/others/GUI/GUIimage/Login.png);\n"
"background-color: transparent;")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(GUI_main)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 320, 131, 51))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border-image: url(E:/others/others/GUI/GUIimage/Exit.png);\n"
"background-color: transparent;")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(GUI_main)
        QtCore.QMetaObject.connectSlotsByName(GUI_main)

    def retranslateUi(self, GUI_main):
        _translate = QtCore.QCoreApplication.translate
        GUI_main.setWindowTitle(_translate("GUI_main", "GUI_main"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUI_main = QtWidgets.QWidget()
    ui = Ui_GUI_main()
    ui.setupUi(GUI_main)
    GUI_main.show()
    sys.exit(app.exec_())
